# HTTP Server (Tomcat) Port
server: 
  port: 4444
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: true
spring:
   application:
     name: project-brijframework-inventory
   main:
     allow-bean-definition-overriding: true
   datasource:
     driverClassName: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/brijframework-inventory
     username: root
     password: root
     show-sql: true
   jpa: 
     hibernate: 
       dialect: org.hibernate.dialect.MySQLDialect
       ddl-auto: update
       format_sql: true
       show_sql: true
       naming: 
         physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:1111/eureka/
security:
    oauth2:
       resource:
         token-info-uri: http://localhost:8080/oauth/check_token
       client:        
         client-id: client
         client-secret: password

